name: Unit Tests
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

permissions:
      id-token: write
      contents: read
      checks: write

jobs:
  tests:
    name: Unit Testing
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Checkout  
      uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.x'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
    - name: Run Unit Tests
      run: |
          python -m unittest discover
